# Generated by Django 4.2.5 on 2023-10-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_selling_price_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AlterField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='imagess'),
        ),
    ]
